### ISSUE TITLE
something's wrong with map.Put

### ISSUE THREAD

**Issue by majek** [andrewkroh/go-ebpf#3]
I call map.Put
```
	var x1 bKey
	var x2 bValue
	x1 = 1
	x2 = 2
	bpfMap.Put(&x1, &x2)
```
Details are irrelevant, I think this should be reproducilbe with any map type and k/v size. The problem? Strace shows the "flags" field is set to value 8 which is wrong:

```
[pid 77491] bpf(BPF_MAP_UPDATE_ELEM, {map_fd=7, key=0xc420014850, value=0xc420014858, flags=0x8 /* BPF_??? */}, 32) = -1 EINVAL (Invalid argument)
```

**Comment by andrewkroh** [comment]
0x8 doesn't appear to be a valid flag for that call. But how does this relate to this probject? Perhaps this was meant for https://github.com/iovisor/gobpf?

**Comment by majek** [comment]
Apologies. I got lost in a thousand open tabs. This should be a ticket for https://github.com/nathanjsweet/ebpf .
