### ISSUE TITLE
Can i use go-ebpf to compile restricted C code to ebpf bytecode?

### ISSUE THREAD

**Issue by tsinhi** [andrewkroh/go-ebpf#5]
Hi, i'm just looking for a tool which can comiple C(restricted) to ebpf bytecode without clang/llvm.
i read the readme.md file ,it says like as follows:
>  The bytecode is shipped with the Go program to avoid having a runtime dependency on clang and llc “.

Does it means I can use go-ebpf for compiling C to ebpf bytecode? 
Thanks!

，

**Comment by andrewkroh** [comment]
No. The examples in this package require LLVM at build time. Then they ship the bytecode as part of the binary.
